In [1]:
import warnings

warnings.simplefilter(action='ignore', category=FutureWarning)

import numpy as np
import pandas as pd

import pathlib

from sklearn.model_selection import ParameterGrid
from sklearn.metrics import auc, roc_auc_score
from sklearn.utils import check_random_state
from joblib import Parallel, delayed

from sklearn.ensemble import IsolationForest

base_dir = pathlib.Path('/Users/vaibhav/MiscProjects/anomaly-detection')

In [2]:
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [3]:
# aloi-unsupervised-ad.csv

df = pd.read_csv(base_dir/'datasets/aloi-unsupervised-ad.csv', header=None)

In [7]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,0.872812,0.000005,0.0,0.000036,0.0,0.0,0.0,0.0,0.0,0.050327,...,0.014212,0.000104,0.0,0.025490,0.004937,0.000011,0.000054,0.006804,0.015385,o
1,0.975206,0.000000,0.0,0.000651,0.0,0.0,0.0,0.0,0.0,0.007039,...,0.000000,0.000000,0.0,0.004853,0.001582,0.000000,0.000000,0.000201,0.000000,o
2,0.963777,0.000000,0.0,0.002005,0.0,0.0,0.0,0.0,0.0,0.006642,...,0.000000,0.000000,0.0,0.007828,0.002523,0.000000,0.000393,0.003800,0.000000,o
3,0.973246,0.000000,0.0,0.000556,0.0,0.0,0.0,0.0,0.0,0.008979,...,0.000000,0.000000,0.0,0.004392,0.000170,0.000000,0.000000,0.000007,0.000000,o
4,0.960720,0.000000,0.0,0.000656,0.0,0.0,0.0,0.0,0.0,0.013319,...,0.000000,0.000000,0.0,0.010299,0.000561,0.000000,0.000084,0.000264,0.000000,o

In [9]:
df[27] = df[27].apply(lambda x: 1 if x == 'o' else 0)

In [12]:
x = df[list(range(0, 27))].values
y = df[27].values

In [15]:
x_tr, x_ts, y_tr, y_ts = train_test_split(x, y, test_size=0.3, random_state=42)

In [29]:
rf = RandomForestClassifier(n_estimators=100, 
                            criterion='gini', 
                            #max_depth=None, 
                            min_samples_split=100, 
                            #min_samples_leaf=1, 
                            #min_weight_fraction_leaf=0.0, 
                            max_features=5, 
                            n_jobs=4, 
                            random_state=25)

In [30]:
rf = rf.fit(x_tr, y_tr)

In [31]:
y_tr_pred_prob = rf.predict(x_tr)
y_ts_pred_prob = rf.predict(x_ts)

In [32]:
print('train roc auc:', roc_auc_score(y_true=y_tr, y_score=y_tr_pred_prob))
print('test roc auc:', roc_auc_score(y_true=y_ts, y_score=y_ts_pred_prob))

train roc auc: 0.5286686103012633
test roc auc: 0.5083507306889353

In [33]:
# annthyroid-unsupervised-ad.csv

df = pd.read_csv(base_dir/'datasets/annthyroid-unsupervised-ad.csv', header=None)

In [34]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.45,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.061,0.006,0.023,0.087,0.026,o
1,0.61,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.029,0.015,0.061,0.096,0.064,o
2,0.16,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.029,0.019,0.058,0.103,0.056,o
3,0.85,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.114,0.003,0.024,0.061,0.039,o
4,0.75,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.049,0.003,0.005,0.116,0.004,o

In [35]:
df[21] = df[21].apply(lambda x: 1 if x == 'o' else 0)

In [37]:
x = df[list(range(0, 21))].values
y = df[21].values
x_tr, x_ts, y_tr, y_ts = train_test_split(x, y, test_size=0.3, random_state=42)

In [50]:
rf = RandomForestClassifier(n_estimators=100, 
                            criterion='gini', 
                            #max_depth=None, 
                            min_samples_split=70, 
                            #min_samples_leaf=1, 
                            #min_weight_fraction_leaf=0.0, 
                            max_features=1., 
                            n_jobs=4, 
                            random_state=25)

rf = rf.fit(x_tr, y_tr)
y_tr_pred_prob = rf.predict(x_tr)
y_ts_pred_prob = rf.predict(x_ts)

print('train roc auc:', roc_auc_score(y_true=y_tr, y_score=y_tr_pred_prob))
print('test roc auc:', roc_auc_score(y_true=y_ts, y_score=y_ts_pred_prob))

train roc auc: 0.9663327105212294
test roc auc: 0.9677267943842529

In [52]:
# breast-cancer-unsupervised-ad.csv

df = pd.read_csv(base_dir/'datasets/breast-cancer-unsupervised-ad.csv', header=None)

In [53]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,o
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,o
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,o
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,o
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,o

In [55]:
df[30] = df[30].apply(lambda x: 1 if x == 'o' else 0)
x = df[list(range(0, 30))].values
y = df[30].values
x_tr, x_ts, y_tr, y_ts = train_test_split(x, y, test_size=0.3, random_state=42)

In [61]:
rf = RandomForestClassifier(n_estimators=100, 
                            criterion='gini', 
                            #max_depth=None, 
                            min_samples_split=2, 
                            #min_samples_leaf=1, 
                            #min_weight_fraction_leaf=0.0, 
                            max_features=1., 
                            n_jobs=4, 
                            random_state=25)

rf = rf.fit(x_tr, y_tr)
y_tr_pred_prob = rf.predict(x_tr)
y_ts_pred_prob = rf.predict(x_ts)

print('train roc auc:', roc_auc_score(y_true=y_tr, y_score=y_tr_pred_prob))
print('test roc auc:', roc_auc_score(y_true=y_ts, y_score=y_ts_pred_prob))

train roc auc: 1.0
test roc auc: 0.8

In [62]:
# shuttle-unsupervised-ad.csv

df = pd.read_csv(base_dir/'datasets/shuttle-unsupervised-ad.csv', header=None)

In [63]:
df.head()

       0    1      2    3     4     5    6      7      8  9
0  108.0  3.0  109.0  0.0  72.0   7.0  1.0   36.0   36.0  o
1   81.0  0.0   84.0  0.0 -14.0  -2.0  4.0  100.0   96.0  o
2   81.0  0.0   84.0  0.0 -20.0  16.0  4.0  105.0  102.0  o
3   76.0 -1.0   81.0  0.0 -42.0  -3.0  5.0  125.0  120.0  o
4  105.0  0.0  107.0  2.0  70.0   0.0  1.0   37.0   36.0  o

In [64]:
df[9] = df[9].apply(lambda x: 1 if x == 'o' else 0)
x = df[list(range(0, 9))].values
y = df[9].values
x_tr, x_ts, y_tr, y_ts = train_test_split(x, y, test_size=0.3, random_state=42)

In [66]:
rf = RandomForestClassifier(n_estimators=100, 
                            criterion='gini', 
                            #max_depth=None, 
                            min_samples_split=50, 
                            #min_samples_leaf=1, 
                            #min_weight_fraction_leaf=0.0, 
                            max_features=1., 
                            n_jobs=4, 
                            random_state=25)

rf = rf.fit(x_tr, y_tr)
y_tr_pred_prob = rf.predict(x_tr)
y_ts_pred_prob = rf.predict(x_ts)

print('train roc auc:', roc_auc_score(y_true=y_tr, y_score=y_tr_pred_prob))
print('test roc auc:', roc_auc_score(y_true=y_ts, y_score=y_ts_pred_prob))

train roc auc: 0.9788617886178862
test roc auc: 0.9809885931558935

In [67]:
# speech-unsupervised-ad.csv

df = pd.read_csv(base_dir/'datasets/speech-unsupervised-ad.csv', header=None)

In [68]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,391,392,393,394,395,396,397,398,399,400
0,-0.35069,0.52721,-1.62470,-1.334000,-1.03020,1.24750,-0.98067,-1.55870,-0.061233,1.048200,...,0.570960,-1.19840,2.168600,-0.30353,1.21620,-0.607070,0.503820,-0.45571,0.86283,o
1,-0.42537,-0.08818,0.84575,0.881570,1.35690,0.74894,-1.68620,0.46151,0.585700,0.775950,...,-0.582980,-0.35666,-0.638000,0.64106,-0.94488,-1.069700,-0.024029,0.28696,-0.12374,o
2,-1.22100,0.43960,-0.06303,0.709530,0.95079,-0.21874,-1.24850,-1.62860,-1.339700,-1.858500,...,-0.042742,2.77110,1.549400,-1.75680,-0.91595,-0.078469,0.097137,-0.55111,0.69951,o
3,-0.30132,0.55221,0.13769,0.715290,0.99311,-0.16959,-0.93405,-0.94825,-0.750880,0.003107,...,-0.103520,2.53710,2.096000,-1.43680,-1.05230,-0.070276,-0.539810,-1.10380,0.70562,o
4,0.31292,0.42762,0.50348,0.005489,-0.94274,-0.17619,-0.50775,-0.46445,0.694750,0.376040,...,1.060700,1.39660,0.096776,-1.18360,-0.37802,0.357150,1.278600,-0.40139,0.11640,o

In [69]:
df[400] = df[400].apply(lambda x: 1 if x == 'o' else 0)
x = df[list(range(0, 400))].values
y = df[400].values
x_tr, x_ts, y_tr, y_ts = train_test_split(x, y, test_size=0.3, random_state=42)

In [75]:
rf = RandomForestClassifier(n_estimators=100, 
                            criterion='gini', 
                            #max_depth=None, 
                            min_samples_split=20, 
                            #min_samples_leaf=1, 
                            #min_weight_fraction_leaf=0.0, 
                            max_features=50, 
                            n_jobs=4, 
                            random_state=25)

rf = rf.fit(x_tr, y_tr)
y_tr_pred_prob = rf.predict(x_tr)
y_ts_pred_prob = rf.predict(x_ts)

print('train roc auc:', roc_auc_score(y_true=y_tr, y_score=y_tr_pred_prob))
print('test roc auc:', roc_auc_score(y_true=y_ts, y_score=y_ts_pred_prob))

train roc auc: 0.5769230769230769
test roc auc: 0.5

In [79]:
with open(base_dir/'datasets/bank.csv', 'wb') as ofb:
    for i in range(1, 6):
        fname = 'datasets/data/' + str(i) + 'year.arff'
        with open(base_dir/fname, 'rb') as ifb:
            for j, line in enumerate(ifb):
                if j >= 69:
                    ofb.write(line)

In [89]:
# bank.csv

df = pd.read_csv(base_dir/'datasets/bank2.csv', header=None)

In [90]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,64
0,0.200550,0.37951,0.39641,2.0472,32.3510,0.38825,0.249760,1.33050,1.1389,0.50494,...,0.121960,0.39718,0.87804,0.001924,8.4160,5.1372,82.658,4.4158,7.4277,0
1,0.209120,0.49988,0.47225,1.9447,14.7860,0.00000,0.258340,0.99601,1.6996,0.49788,...,0.121300,0.42002,0.85300,0.000000,4.1486,3.2732,107.350,3.4000,60.9870,0
2,0.248660,0.69592,0.26713,1.5548,-1.1523,0.00000,0.309060,0.43695,1.3090,0.30408,...,0.241140,0.81774,0.76599,0.694840,4.9909,3.9510,134.270,2.7185,5.2078,0
3,0.081483,0.30734,0.45879,2.4928,51.9520,0.14988,0.092704,1.86610,1.0571,0.57353,...,0.054015,0.14207,0.94598,0.000000,4.5746,3.6147,86.435,4.2228,5.5497,0
4,0.187320,0.61323,0.22960,1.4063,-7.3128,0.18732,0.187320,0.63070,1.1559,0.38677,...,0.134850,0.48431,0.86515,0.124440,6.3985,4.3158,127.210,2.8692,7.8980,0

In [92]:
#df[400] = df[400].apply(lambda x: 1 if x == 'o' else 0)
x = df[list(range(0, 64))].values
y = df[64].values
x_tr, x_ts, y_tr, y_ts = train_test_split(x, y, test_size=0.3, random_state=42)

In [95]:
rf = RandomForestClassifier(n_estimators=100, 
                            criterion='gini', 
                            #max_depth=None, 
                            min_samples_split=100, 
                            #min_samples_leaf=1, 
                            #min_weight_fraction_leaf=0.0, 
                            max_features=25, 
                            n_jobs=4, 
                            random_state=25)

rf = rf.fit(x_tr, y_tr)
y_tr_pred_prob = rf.predict(x_tr)
y_ts_pred_prob = rf.predict(x_ts)

print('train roc auc:', roc_auc_score(y_true=y_tr, y_score=y_tr_pred_prob))
print('test roc auc:', roc_auc_score(y_true=y_ts, y_score=y_ts_pred_prob))

train roc auc: 0.6630540872150695
test roc auc: 0.6442303092751315